INSERT INTO "DimCustomer"(customerid,category,country,industry)
VALUES
(1,'Individual','Indonesia','Engineering'),
(614,'Individual','United States','Product Management'),
(615,'Individual','China','Services'),
(616,'Individual','Russia','Accounting'),
(617,'Individual','Chile','Business Development'),
(618,'Individual','Nicaragua','Human Resources'),
(41,'Company','Brazil','Marketing'),
(619,'Individual','Russia','Business Development'),
(620,'Individual','China','Business Development'),
(956,'Individual','Peru','Research and Development'),
(621,'Individual','Angola','Services'),
(622,'Individual','Poland','Legal'),
(623,'Individual','Italy','Training'),
(624,'Individual','Indonesia','Sales'),
(625,'Individual','Portugal','Services'),
(626,'Individual','Mexico','Engineering'),
(40,'Individual','Portugal','Human Resources'),
(627,'Company','Philippines','Services'),
(628,'Individual','France','Business Development'),
(629,'Company','France','Training'),
(630,'Individual','Indonesia','Services'),
(631,'Company','Poland','Marketing'),
(632,'Company','Brunei','Training'),
(633,'Individual','Russia','Sales'),
(634,'Company','Mexico','Business Development'),
(39,'Company','Ivory Coast','Engineering'),
(613,'Individual','Czech Republic','Sales'),
(955,'Individual','Sudan','Accounting'),
(612,'Individual','Argentina','Product Management'),
(611,'Individual','Uzbekistan','Engineering'),
(591,'Individual','China','Support'),
(592,'Company','Philippines','Training'),
(593,'Company','China','Services'),
(958,'Company','Indonesia','Sales'),
(594,'Individual','Germany','Engineering'),
(595,'Company','Portugal','Legal'),
(44,'Individual','Paraguay','Human Resources'),
(596,'Company','Philippines','Human Resources'),
(597,'Individual','South Africa','Accounting'),
(598,'Company','United Kingdom','Training'),
(599,'Individual','Cyprus','Engineering'),
(600,'Individual','Sweden','Sales'),
(601,'Individual','Nigeria','Training'),
(602,'Individual','China','Human Resources'),
(603,'Individual','Iran','Engineering'),
(43,'Individual','Portugal','Marketing'),
(604,'Individual','Sweden','Human Resources'),
(998,'Individual','China','Engineering'),
(605,'Individual','Philippines','Engineering'),
(606,'Individual','Poland','Marketing'),
(607,'Individual','Philippines','Support'),
(957,'Company','Philippines','Legal'),
(608,'Company','Dominican Republic','Support'),
(609,'Individual','Indonesia','Training'),
(610,'Company','China','Legal'),
(42,'Individual','Poland','Marketing'),
(590,'Company','China','Human Resources'),
(635,'Individual','Czech Republic','Sales'),
(637,'Company','Madagascar','Support'),
(953,'Company','Vietnam','Business Development'),
(663,'Company','Cuba','Research and Development'),
(664,'Company','Poland','Sales'),
(665,'Company','France','Support'),
(35,'Individual','Republic of the Congo','Business Development'),
(666,'Individual','Japan','Legal'),
(667,'Individual','China','Training'),
(668,'Company','France','Services'),
(669,'Individual','Pakistan','Engineering'),
(670,'Individual','Brazil','Sales'),
(671,'Individual','Czech Republic','Support'),
(672,'Individual','Slovakia','Support'),
(673,'Company','China','Product Management'),
(674,'Company','Ukraine','Support'),
(34,'Company','Croatia','Research and Development'),
(675,'Company','France','Marketing'),
(952,'Individual','China','Sales'),
(676,'Individual','Lithuania','Accounting'),
(677,'Individual','Dominican Republic','Human Resources'),
(678,'Company','China','Product Management'),
(679,'Individual','Latvia','Support'),
(680,'Company','France','Services'),
(681,'Individual','Mauritius','Accounting'),
(33,'Individual','China','Business Development'),
(682,'Company','China','Sales'),
(662,'Individual','Nigeria','Training'),
(636,'Company','Tanzania','Legal'),
(661,'Company','China','Services'),
(659,'Individual','Poland','Engineering'),
(638,'Company','Colombia','Support'),
(639,'Individual','Finland','Legal'),
(640,'Company','Colombia','Support'),
(641,'Individual','Vietnam','Engineering'),
(642,'Company','China','Business Development'),
(38,'Individual','Philippines','Sales'),
(643,'Company','Egypt','Support'),
(644,'Individual','Slovenia','Legal'),
(645,'Individual','Indonesia','Human Resources'),
(646,'Individual','Portugal','Sales'),
(647,'Company','Indonesia','Business Development'),
(648,'Individual','Russia','Marketing'),
(954,'Individual','Armenia','Accounting'),
(649,'Company','Thailand','Services'),
(37,'Company','Indonesia','Business Development'),
(650,'Individual','Luxembourg','Engineering'),
(651,'Company','Philippines','Support'),
(652,'Company','Poland','Sales'),
(653,'Company','Cape Verde','Training'),
(654,'Company','China','Legal'),
(655,'Individual','China','Engineering'),
(656,'Individual','Cuba','Training'),
(657,'Company','Paraguay','Services'),
(658,'Company','Bolivia','Human Resources'),
(36,'Company','Ukraine','Product Management'),
(660,'Individual','China','Marketing'),
(589,'Company','Philippines','Research and Development'),
(588,'Company','France','Product Management'),
(45,'Individual','Colombia','Accounting'),
(517,'Company','Bosnia and Herzegovina','Human Resources'),
(518,'Individual','Sri Lanka','Training'),
(519,'Individual','Indonesia','Human Resources'),
(520,'Individual','Indonesia','Training'),
(521,'Individual','Nigeria','Support'),
(522,'Company','Indonesia','Engineering'),
(523,'Company','China','Business Development'),
(524,'Company','China','Sales'),
(53,'Company','China','Services'),
(963,'Company','China','Support'),
(525,'Individual','China','Training'),
(526,'Company','China','Legal'),
(527,'Individual','Canada','Research and Development'),
(528,'Company','Indonesia','Support'),
(529,'Company','Russia','Services'),
(530,'Individual','China','Engineering'),
(531,'Company','Portugal','Legal'),
(532,'Individual','China','Services'),
(52,'Individual','Moldova','Legal'),
(533,'Company','China','Business Development'),
(534,'Company','Russia','Services'),
(535,'Individual','Poland','Training'),
(536,'Individual','Honduras','Human Resources'),
(537,'Individual','United States','Research and Development'),
(538,'Individual','Russia','Training'),
(54,'Individual','China','Services'),
(962,'Individual','Czech Republic','Legal'),
(516,'Company','Argentina','Legal'),
(514,'Individual','Somalia','Legal'),
(494,'Company','Thailand','Engineering'),
(495,'Individual','Palestinian Territory','Business Development'),
(496,'Individual','Ukraine','Marketing'),
(965,'Company','Nigeria','Marketing'),
(497,'Company','Bolivia','Business Development'),
(498,'Company','China','Marketing'),
(499,'Individual','French Guiana','Legal'),
(500,'Individual','China','Accounting'),
(501,'Individual','Philippines','Marketing'),
(56,'Individual','Sweden','Business Development'),
(997,'Company','Mongolia','Sales'),
(502,'Individual','Ukraine','Legal'),
(503,'Individual','Yemen','Support'),
(504,'Company','United States','Research and Development'),
(505,'Individual','France','Business Development'),
(506,'Individual','Indonesia','Business Development'),
(507,'Individual','Russia','Engineering'),
(508,'Company','Peru','Engineering'),
(509,'Company','Kenya','Training'),
(55,'Individual','China','Engineering'),
(510,'Individual','Portugal','Support'),
(964,'Individual','Brazil','Training'),
(511,'Individual','Armenia','Legal'),
(512,'Company','Russia','Sales'),
(513,'Company','Indonesia','Training'),
(515,'Individual','Brazil','Legal'),
(539,'Company','Bosnia and Herzegovina','Business Development'),
(51,'Company','Paraguay','Support'),
(540,'Company','Indonesia','Marketing'),
(566,'Individual','Peru','Legal'),
(567,'Company','Vietnam','Human Resources'),
(568,'Company','Indonesia','Support'),
(569,'Individual','China','Research and Development'),
(570,'Company','Czech Republic','Business Development'),
(571,'Company','United States','Legal'),
(47,'Company','United States','Training'),
(572,'Company','United States','Engineering'),
(573,'Individual','Brazil','Support'),
(574,'Company','Equatorial Guinea','Marketing'),
(575,'Individual','Guinea','Training'),
(576,'Individual','China','Engineering'),
(577,'Individual','Armenia','Research and Development'),
(578,'Individual','China','Support'),
(579,'Company','France','Marketing'),
(46,'Individual','Mexico','Product Management'),
(959,'Individual','Libya','Legal'),
(580,'Individual','Madagascar','Research and Development'),
(581,'Company','Indonesia','Support'),
(582,'Individual','Poland','Marketing'),
(583,'Company','Georgia','Marketing'),
(584,'Company','Canada','Research and Development'),
(585,'Individual','Brazil','Support'),
(586,'Company','China','Product Management'),
(587,'Individual','China','Sales'),
(960,'Individual','Indonesia','Human Resources'),
(565,'Individual','Portugal','Services'),
(48,'Individual','Indonesia','Business Development'),
(564,'Individual','Russia','Marketing'),
(541,'Company','Russia','Engineering'),
(542,'Individual','Afghanistan','Product Management'),
(543,'Company','United States','Marketing'),
(544,'Individual','South Korea','Services'),
(545,'Individual','China','Sales'),
(546,'Individual','Greece','Research and Development'),
(547,'Company','Indonesia','Services'),
(548,'Individual','United States','Training'),
(50,'Company','Paraguay','Business Development'),
(549,'Company','Kyrgyzstan','Engineering'),
(550,'Company','Philippines','Engineering'),
(551,'Individual','Russia','Business Development'),
(683,'Company','Russia','Business Development'),
(961,'Individual','China','Services'),
(553,'Company','Belarus','Accounting'),
(554,'Company','Japan','Accounting'),
(555,'Company','Portugal','Research and Development'),
(49,'Company','China','Sales'),
(556,'Company','China','Product Management'),
(557,'Company','Finland','Services'),
(558,'Company','Mexico','Training'),
(559,'Individual','Indonesia','Legal'),
(560,'Company','Nicaragua','Engineering'),
(561,'Individual','Indonesia','Sales'),
(562,'Individual','Belarus','Research and Development'),
(563,'Individual','China','Sales'),
(552,'Individual','China','Human Resources'),
(684,'Individual','Mexico','Training'),
(685,'Individual','Ukraine','Support'),
(686,'Individual','Indonesia','Human Resources'),
(17,'Company','France','Services'),
(808,'Company','China','Legal'),
(809,'Company','Philippines','Services'),
(810,'Individual','China','Human Resources'),
(811,'Individual','Benin','Human Resources'),
(812,'Company','China','Human Resources'),
(813,'Company','Serbia','Human Resources'),
(942,'Individual','Indonesia','Services'),
(814,'Individual','Ukraine','Legal'),
(815,'Company','Macedonia','Product Management'),
(16,'Individual','Ukraine','Sales'),
(816,'Company','Thailand','Marketing'),
(817,'Individual','Honduras','Research and Development'),
(818,'Individual','Portugal','Human Resources'),
(819,'Company','Thailand','Legal'),
(820,'Company','United States','Accounting'),
(821,'Individual','Colombia','Accounting'),
(822,'Individual','Tanzania','Sales'),
(823,'Company','Bosnia and Herzegovina','Engineering'),
(15,'Individual','Thailand','Engineering'),
(824,'Individual','China','Legal'),
(1000,'Company','China','Legal'),
(825,'Company','Brazil','Support'),
(826,'Individual','Argentina','Research and Development'),
(827,'Individual','Argentina','Marketing'),
(807,'Company','Portugal','Product Management'),
(941,'Individual','Denmark','Human Resources'),
(806,'Company','China','Legal'),
(804,'Company','China','Human Resources'),
(784,'Individual','Russia','Marketing'),
(20,'Individual','Armenia','Services'),
(785,'Company','China','Research and Development'),
(786,'Individual','Philippines','Training'),
(944,'Company','Greece','Legal'),
(787,'Company','Japan','Research and Development'),
(788,'Individual','China','Marketing'),
(789,'Company','Poland','Accounting'),
(790,'Individual','Ethiopia','Accounting'),
(791,'Company','Vietnam','Marketing'),
(19,'Individual','China','Business Development'),
(792,'Individual','Indonesia','Engineering'),
(793,'Individual','Bangladesh','Human Resources'),
(794,'Company','China','Legal'),
(795,'Company','Dominican Republic','Accounting'),
(796,'Company','Venezuela','Training'),
(797,'Individual','Indonesia','Legal'),
(798,'Company','Egypt','Training'),
(799,'Company','Sweden','Engineering'),
(18,'Individual','Ecuador','Engineering'),
(943,'Individual','China','Human Resources'),
(800,'Company','China','Human Resources'),
(801,'Company','China','Support'),
(802,'Company','Brazil','Business Development'),
(803,'Individual','Brazil','Business Development'),
(805,'Company','China','Services'),
(828,'Company','Nigeria','Services'),
(829,'Company','Canada','Accounting'),
(830,'Company','Costa Rica','Support'),
(939,'Company','Russia','Support'),
(856,'Company','Sweden','Engineering'),
(857,'Individual','Russia','Product Management'),
(858,'Individual','Tanzania','Accounting'),
(859,'Individual','Nigeria','Product Management'),
(860,'Company','Brazil','Sales'),
(861,'Company','Indonesia','Business Development'),
(862,'Company','United States','Accounting'),
(10,'Company','New Zealand','Engineering'),
(863,'Company','Finland','Services'),
(864,'Individual','Liechtenstein','Training'),
(865,'Individual','Japan','Training'),
(866,'Company','Peru','Accounting'),
(867,'Company','Thailand','Accounting'),
(868,'Company','Philippines','Engineering'),
(938,'Individual','Sweden','Engineering'),
(869,'Individual','Brazil','Legal'),
(9,'Company','Russia','Support'),
(870,'Individual','Tunisia','Marketing'),
(871,'Company','China','Training'),
(872,'Individual','Uganda','Engineering'),
(873,'Company','Canada','Human Resources'),
(874,'Individual','China','Research and Development'),
(875,'Individual','China','Engineering'),
(876,'Company','Cape Verde','Services'),
(855,'Company','Poland','Legal'),
(11,'Individual','Myanmar','Training'),
(854,'Individual','China','Research and Development'),
(853,'Individual','Russia','Support'),
(831,'Individual','Indonesia','Product Management'),
(14,'Company','Poland','Research and Development'),
(832,'Individual','Peru','Support'),
(833,'Individual','Burkina Faso','Sales'),
(834,'Company','Libya','Services'),
(835,'Company','Portugal','Human Resources'),
(836,'Company','Yemen','Services'),
(837,'Company','China','Human Resources'),
(838,'Individual','Russia','Human Resources'),
(13,'Individual','China','Human Resources'),
(839,'Individual','Russia','Services'),
(840,'Individual','Philippines','Product Management'),
(783,'Company','Ukraine','Accounting'),
(841,'Company','Peru','Accounting'),
(842,'Individual','Djibouti','Sales'),
(843,'Company','China','Services'),
(844,'Individual','Ukraine','Support'),
(845,'Individual','Brazil','Business Development'),
(846,'Company','France','Research and Development'),
(12,'Individual','China','Legal'),
(847,'Individual','Philippines','Research and Development'),
(848,'Company','Russia','Sales'),
(849,'Company','Portugal','Legal'),
(850,'Company','Brazil','Training'),
(851,'Company','Philippines','Sales'),
(852,'Company','China','Product Management'),
(940,'Company','Indonesia','Services'),
(57,'Company','Indonesia','Engineering'),
(782,'Individual','China','Marketing'),
(780,'Individual','Indonesia','Business Development'),
(711,'Individual','Serbia','Support'),
(712,'Company','Indonesia','Sales'),
(713,'Company','Belarus','Human Resources'),
(29,'Individual','Russia','Training'),
(714,'Individual','China','Sales'),
(999,'Company','China','Business Development'),
(715,'Individual','United States','Product Management'),
(716,'Individual','Argentina','Business Development'),
(717,'Company','Bangladesh','Sales'),
(949,'Individual','Russia','Accounting'),
(718,'Company','Peru','Product Management'),
(719,'Company','Colombia','Research and Development'),
(720,'Company','China','Research and Development'),
(721,'Company','Russia','Support'),
(28,'Company','Kiribati','Business Development'),
(722,'Individual','Sweden','Sales'),
(723,'Company','Pakistan','Legal'),
(724,'Individual','Luxembourg','Accounting'),
(725,'Individual','Argentina','Services'),
(726,'Company','China','Product Management'),
(727,'Company','Cameroon','Engineering'),
(728,'Individual','Kyrgyzstan','Accounting'),
(27,'Company','Cayman Islands','Legal'),
(729,'Individual','Norway','Product Management'),
(730,'Individual','China','Marketing'),
(710,'Individual','Czech Republic','Human Resources'),
(731,'Individual','Indonesia','Support'),
(709,'Company','Lebanon','Business Development'),
(707,'Individual','Indonesia','Accounting'),
(687,'Company','China','Marketing'),
(688,'Individual','Russia','Business Development'),
(689,'Individual','Indonesia','Legal'),
(32,'Company','Colombia','Sales'),
(951,'Individual','China','Research and Development'),
(690,'Company','Philippines','Product Management'),
(691,'Individual','North Korea','Legal'),
(692,'Company','Poland','Training'),
(693,'Individual','Portugal','Services'),
(694,'Company','Canada','Support'),
(695,'Company','Greece','Engineering'),
(696,'Individual','Russia','Human Resources'),
(697,'Individual','Iran','Engineering'),
(31,'Company','Kazakhstan','Research and Development'),
(698,'Company','Indonesia','Sales'),
(699,'Company','United States','Marketing'),
(700,'Company','Peru','Marketing'),
(701,'Company','Jordan','Product Management'),
(702,'Company','Sweden','Marketing'),
(703,'Individual','Indonesia','Accounting'),
(950,'Company','Philippines','Support'),
(704,'Individual','Russia','Legal'),
(705,'Company','Indonesia','Training'),
(30,'Individual','China','Research and Development'),
(706,'Company','Portugal','Marketing'),
(708,'Individual','China','Support'),
(948,'Company','China','Marketing'),
(732,'Company','Sri Lanka','Legal'),
(733,'Company','Costa Rica','Legal'),
(759,'Individual','China','Support'),
(23,'Company','Croatia','Research and Development'),
(760,'Company','Russia','Training'),
(761,'Individual','China','Research and Development'),
(762,'Company','France','Accounting'),
(763,'Individual','Slovenia','Business Development'),
(764,'Individual','Kazakhstan','Sales'),
(765,'Company','Austria','Accounting'),
(766,'Individual','Dominican Republic','Human Resources'),
(767,'Company','Philippines','Sales'),
(768,'Company','Russia','Research and Development'),
(22,'Company','Portugal','Business Development'),
(769,'Company','Mexico','Accounting'),
(770,'Individual','China','Product Management'),
(771,'Company','Bangladesh','Product Management'),
(772,'Individual','Philippines','Human Resources'),
(945,'Individual','Colombia','Marketing'),
(773,'Individual','Thailand','Training'),
(774,'Individual','Albania','Accounting'),
(775,'Company','Philippines','Training'),
(21,'Company','Pakistan','Support'),
(776,'Individual','China','Business Development'),
(777,'Individual','Georgia','Training'),
(778,'Individual','China','Human Resources'),
(779,'Company','Niger','Product Management'),
(946,'Individual','Indonesia','Business Development'),
(758,'Company','Nicaragua','Support'),
(757,'Company','Czech Republic','Support'),
(756,'Company','China','Product Management'),
(734,'Company','Philippines','Sales'),
(735,'Individual','China','Training'),
(736,'Company','Brazil','Research and Development'),
(26,'Individual','China','Product Management'),
(737,'Individual','China','Legal'),
(738,'Individual','Sweden','Product Management'),
(739,'Individual','Thailand','Marketing'),
(740,'Company','Russia','Engineering'),
(741,'Company','China','Services'),
(742,'Individual','China','Services'),
(743,'Individual','China','Business Development'),
(744,'Company','China','Product Management'),
(781,'Company','Yemen','Engineering'),
(25,'Company','Czech Republic','Sales'),
(745,'Individual','Philippines','Legal'),
(746,'Individual','Portugal','Product Management'),
(747,'Company','Russia','Marketing'),
(748,'Company','Venezuela','Product Management'),
(749,'Individual','Portugal','Services'),
(750,'Individual','China','Sales'),
(751,'Company','Serbia','Legal'),
(752,'Individual','Peru','Legal'),
(24,'Individual','Denmark','Product Management'),
(753,'Company','China','Business Development'),
(754,'Individual','Brazil','Sales'),
(755,'Company','Dominican Republic','Legal'),
(947,'Individual','China','Engineering'),
(877,'Individual','Brazil','Engineering'),
(493,'Individual','Spain','Business Development'),
(491,'Individual','Philippines','Product Management'),
(228,'Company','China','Business Development'),
(229,'Company','Vietnam','Product Management'),
(230,'Individual','Palestinian Territory','Marketing'),
(231,'Individual','Indonesia','Services'),
(232,'Company','Brazil','Human Resources'),
(233,'Company','Hungary','Sales'),
(90,'Company','Venezuela','Legal'),
(234,'Company','South Africa','Services'),
(984,'Company','Sweden','Services'),
(235,'Company','Egypt','Marketing'),
(236,'Individual','China','Services'),
(237,'Individual','Honduras','Services'),
(238,'Individual','Indonesia','Accounting'),
(239,'Individual','China','Business Development'),
(240,'Individual','Philippines','Research and Development'),
(241,'Individual','China','Support'),
(89,'Individual','Philippines','Legal'),
(242,'Individual','China','Marketing'),
(243,'Company','Argentina','Sales'),
(244,'Individual','China','Services'),
(245,'Company','Croatia','Engineering'),
(246,'Individual','China','Research and Development'),
(247,'Individual','Brazil','Human Resources'),
(248,'Company','Philippines','Marketing'),
(983,'Individual','China','Marketing'),
(227,'Individual','Philippines','Human Resources'),
(88,'Company','Indonesia','Engineering'),
(226,'Individual','Portugal','Sales'),
(225,'Individual','China','Services'),
(204,'Company','Brazil','Support'),
(205,'Company','Canada','Business Development'),
(206,'Company','Ghana','Support'),
(207,'Individual','China','Support'),
(986,'Company','Peru','Product Management'),
(208,'Individual','China','Sales'),
(209,'Individual','China','Services'),
(93,'Company','France','Accounting'),
(210,'Individual','China','Marketing'),
(211,'Company','Guatemala','Sales'),
(212,'Individual','China','Human Resources'),
(213,'Company','Philippines','Marketing'),
(214,'Individual','Japan','Training'),
(215,'Individual','United States','Research and Development'),
(216,'Company','Portugal','Sales'),
(217,'Individual','Brazil','Research and Development'),
(92,'Company','Thailand','Services'),
(218,'Individual','China','Marketing'),
(219,'Company','Mongolia','Product Management'),
(220,'Individual','France','Engineering'),
(221,'Company','Argentina','Human Resources'),
(985,'Company','Mexico','Marketing'),
(222,'Individual','China','Sales'),
(223,'Individual','Portugal','Human Resources'),
(224,'Individual','Lebanon','Research and Development'),
(91,'Company','Indonesia','Business Development'),
(203,'Company','United States','Training'),
(249,'Company','China','Human Resources'),
(251,'Individual','Kazakhstan','Sales'),
(981,'Individual','Philippines','Human Resources'),
(277,'Individual','Bulgaria','Legal'),
(278,'Individual','Namibia','Marketing'),
(279,'Company','Palestinian Territory','Support'),
(280,'Company','Indonesia','Marketing'),
(84,'Company','France','Legal'),
(281,'Company','Brazil','Business Development'),
(995,'Company','Mauritius','Legal'),
(282,'Company','Japan','Human Resources'),
(283,'Company','China','Accounting'),
(284,'Individual','Mongolia','Accounting'),
(285,'Company','Colombia','Engineering'),
(286,'Company','China','Training'),
(287,'Individual','Portugal','Research and Development'),
(288,'Individual','Ethiopia','Services'),
(83,'Individual','China','Research and Development'),
(289,'Company','Ukraine','Legal'),
(290,'Individual','Nigeria','Research and Development'),
(980,'Company','Sweden','Business Development'),
(291,'Individual','Ecuador','Legal'),
(292,'Company','Japan','Legal'),
(293,'Company','South Africa','Legal'),
(294,'Individual','China','Legal'),
(295,'Individual','Poland','Sales'),
(296,'Individual','Argentina','Services'),
(276,'Company','Poland','Sales'),
(250,'Individual','Central African Republic','Product Management'),
(275,'Company','Indonesia','Engineering'),
(85,'Company','China','Legal'),
(252,'Company','China','Human Resources'),
(253,'Individual','Colombia','Marketing'),
(254,'Individual','Indonesia','Marketing'),
(255,'Company','Russia','Product Management'),
(256,'Company','Indonesia','Research and Development'),
(257,'Company','Guatemala','Business Development'),
(87,'Individual','Poland','Human Resources'),
(258,'Individual','Laos','Marketing'),
(259,'Individual','Czech Republic','Legal'),
(260,'Individual','Ukraine','Training'),
(261,'Company','Syria','Support'),
(262,'Individual','United States','Human Resources'),
(982,'Company','Poland','Research and Development'),
(263,'Company','United States','Engineering'),
(264,'Individual','Brazil','Product Management'),
(86,'Company','Indonesia','Engineering'),
(265,'Company','Indonesia','Support'),
(266,'Individual','Portugal','Sales'),
(267,'Company','Russia','Sales'),
(268,'Company','Portugal','Accounting'),
(269,'Individual','Malaysia','Business Development'),
(270,'Company','Indonesia','Business Development'),
(271,'Company','Indonesia','Training'),
(272,'Individual','Czech Republic','Marketing'),
(273,'Company','China','Engineering'),
(274,'Individual','Ukraine','Accounting'),
(202,'Individual','Morocco','Research and Development'),
(94,'Company','Russia','Product Management'),
(201,'Individual','China','Research and Development'),
(103,'Individual','Pakistan','Engineering'),
(132,'Company','Sweden','Accounting'),
(133,'Company','Brazil','Sales'),
(134,'Individual','China','Sales'),
(135,'Company','Indonesia','Sales'),
(136,'Company','Colombia','Business Development'),
(137,'Company','China','Accounting'),
(138,'Individual','Poland','Business Development'),
(102,'Individual','Russia','Business Development'),
(991,'Company','Poland','Marketing'),
(139,'Individual','United States','Sales'),
(140,'Company','Poland','Training'),
(141,'Individual','Spain','Marketing'),
(142,'Individual','China','Services'),
(143,'Company','Peru','Engineering'),
(144,'Individual','Uzbekistan','Human Resources'),
(145,'Individual','Bosnia and Herzegovina','Product Management'),
(146,'Individual','Cameroon','Support'),
(147,'Company','United States','Engineering'),
(101,'Individual','Iran','Legal'),
(148,'Company','Egypt','Training'),
(149,'Individual','Portugal','Human Resources'),
(150,'Company','Vietnam','Training'),
(151,'Individual','Sierra Leone','Marketing'),
(152,'Individual','Malta','Training'),
(131,'Company','China','Product Management'),
(990,'Company','American Samoa','Business Development'),
(130,'Company','Peru','Human Resources'),
(128,'Company','Indonesia','Legal'),
(106,'Company','Bulgaria','Product Management'),
(108,'Company','China','Legal'),
(109,'Individual','Portugal','Business Development'),
(110,'Individual','Indonesia','Training'),
(993,'Company','Russia','Accounting'),
(111,'Individual','Indonesia','Marketing'),
(112,'Company','Indonesia','Training'),
(113,'Individual','Portugal','Product Management'),
(114,'Individual','Syria','Business Development'),
(115,'Individual','Albania','Human Resources'),
(105,'Individual','Indonesia','Product Management'),
(116,'Company','Russia','Product Management'),
(117,'Individual','Ukraine','Training'),
(118,'Company','Peru','Accounting'),
(119,'Individual','Sweden','Engineering'),
(120,'Company','Indonesia','Legal'),
(121,'Company','Vietnam','Marketing'),
(122,'Individual','Indonesia','Services'),
(123,'Individual','Indonesia','Sales'),
(104,'Company','Peru','Accounting'),
(124,'Company','Indonesia','Product Management'),
(992,'Company','Egypt','Services'),
(125,'Company','Brazil','Legal'),
(126,'Individual','Indonesia','Research and Development'),
(127,'Company','Sweden','Product Management'),
(129,'Individual','Vietnam','Engineering'),
(153,'Company','Poland','Research and Development'),
(154,'Individual','China','Product Management'),
(100,'Individual','Croatia','Services'),
(988,'Individual','Albania','Services'),
(180,'Company','Russia','Engineering'),
(181,'Individual','Argentina','Accounting'),
(182,'Individual','Thailand','Business Development'),
(183,'Company','Indonesia','Product Management'),
(184,'Company','China','Marketing'),
(185,'Company','Czech Republic','Research and Development'),
(186,'Company','Philippines','Accounting'),
(96,'Company','Philippines','Accounting'),
(187,'Company','Brazil','Legal'),
(188,'Company','Russia','Product Management'),
(189,'Individual','Indonesia','Services'),
(190,'Company','China','Human Resources'),
(191,'Company','Indonesia','Accounting'),
(192,'Individual','France','Engineering'),
(193,'Individual','China','Product Management'),
(95,'Individual','Sri Lanka','Services'),
(987,'Company','Indonesia','Marketing'),
(194,'Individual','Mexico','Product Management'),
(195,'Company','United States','Product Management'),
(196,'Individual','China','Human Resources'),
(197,'Company','Morocco','Product Management'),
(198,'Company','China','Services'),
(199,'Company','China','Engineering'),
(200,'Individual','Indonesia','Engineering'),
(179,'Individual','Philippines','Research and Development'),
(97,'Company','China','Engineering'),
(178,'Individual','Indonesia','Research and Development'),
(177,'Individual','Sweden','Marketing'),
(155,'Individual','Antigua and Barbuda','Product Management'),
(156,'Individual','Albania','Services'),
(157,'Individual','Indonesia','Business Development'),
(158,'Company','Brunei','Research and Development'),
(159,'Individual','Nigeria','Legal'),
(160,'Company','Canada','Sales'),
(161,'Individual','China','Accounting'),
(162,'Company','Czech Republic','Business Development'),
(163,'Individual','Uruguay','Sales'),
(99,'Individual','Ethiopia','Product Management'),
(164,'Individual','Thailand','Training'),
(165,'Company','Czech Republic','Business Development'),
(82,'Individual','Morocco','Marketing'),
(166,'Company','France','Product Management'),
(167,'Individual','Poland','Business Development'),
(168,'Individual','Russia','Legal'),
(169,'Individual','Argentina','Human Resources'),
(170,'Company','Syria','Business Development'),
(98,'Company','Thailand','Business Development'),
(171,'Individual','Albania','Engineering'),
(994,'Individual','Philippines','Human Resources'),
(172,'Company','Croatia','Research and Development'),
(173,'Individual','Poland','Marketing'),
(174,'Company','Croatia','Services'),
(175,'Company','Indonesia','Training'),
(176,'Individual','France','Support'),
(989,'Company','Bulgaria','Support'),
(297,'Company','Bhutan','Sales'),
(298,'Company','China','Training'),
(299,'Company','Germany','Business Development'),
(421,'Individual','Chad','Accounting'),
(422,'Individual','Philippines','Support'),
(66,'Company','China','Marketing'),
(423,'Individual','Philippines','Marketing'),
(424,'Individual','Indonesia','Training'),
(425,'Company','Philippines','Human Resources'),
(426,'Company','Russia','Marketing'),
(427,'Individual','Bosnia and Herzegovina','Engineering'),
(970,'Company','Argentina','Legal'),
(428,'Individual','Sweden','Research and Development'),
(429,'Company','Central African Republic','Training'),
(65,'Company','Indonesia','Training'),
(430,'Company','Portugal','Services'),
(431,'Individual','Czech Republic','Research and Development'),
(432,'Company','China','Support'),
(433,'Individual','Canada','Research and Development'),
(434,'Company','China','Sales'),
(435,'Individual','China','Product Management'),
(436,'Company','Portugal','Research and Development'),
(437,'Company','China','Business Development'),
(438,'Individual','China','Research and Development'),
(64,'Individual','France','Business Development'),
(439,'Individual','Thailand','Research and Development'),
(440,'Individual','China','Legal'),
(441,'Individual','China','Training'),
(420,'Individual','Indonesia','Services'),
(969,'Company','Greece','Support'),
(419,'Individual','Indonesia','Business Development'),
(417,'Company','Philippines','Engineering'),
(397,'Company','Kazakhstan','Business Development'),
(398,'Company','Luxembourg','Product Management'),
(69,'Individual','Nigeria','Business Development'),
(399,'Individual','Yemen','Engineering'),
(400,'Individual','Russia','Research and Development'),
(972,'Company','Peru','Sales'),
(401,'Individual','Brazil','Support'),
(402,'Individual','France','Legal'),
(403,'Individual','Vietnam','Product Management'),
(404,'Individual','Saudi Arabia','Engineering'),
(405,'Individual','Russia','Services'),
(406,'Individual','Yemen','Research and Development'),
(68,'Company','United States','Training'),
(407,'Individual','Malaysia','Engineering'),
(408,'Individual','Canada','Services'),
(409,'Individual','Argentina','Sales'),
(410,'Individual','China','Marketing'),
(411,'Individual','Poland','Product Management'),
(412,'Individual','France','Research and Development'),
(413,'Individual','Malaysia','Engineering'),
(67,'Individual','Brazil','Engineering'),
(414,'Individual','Nigeria','Marketing'),
(971,'Company','China','Product Management'),
(415,'Company','Kuwait','Accounting'),
(416,'Company','North Korea','Training'),
(418,'Individual','Philippines','Accounting'),
(442,'Company','Sweden','Sales'),
(443,'Company','China','Sales'),
(444,'Company','Bolivia','Marketing'),
(967,'Individual','Indonesia','Research and Development'),
(470,'Individual','Vietnam','Training'),
(471,'Individual','Portugal','Services'),
(472,'Individual','Canada','Product Management'),
(473,'Individual','Canada','Product Management'),
(474,'Company','Azerbaijan','Research and Development'),
(475,'Company','Portugal','Accounting'),
(476,'Company','China','Research and Development'),
(477,'Individual','United States','Engineering'),
(59,'Company','Kazakhstan','Services'),
(478,'Company','Portugal','Services'),
(479,'Company','Ethiopia','Human Resources'),
(480,'Individual','Malaysia','Accounting'),
(481,'Company','South Korea','Legal'),
(482,'Individual','Philippines','Engineering'),
(966,'Company','China','Human Resources'),
(483,'Company','Philippines','Engineering'),
(484,'Company','China','Engineering'),
(485,'Company','Poland','Sales'),
(58,'Company','China','Engineering'),
(486,'Individual','China','Services'),
(487,'Individual','Indonesia','Research and Development'),
(488,'Individual','Russia','Research and Development'),
(489,'Individual','Indonesia','Training'),
(490,'Individual','Sweden','Legal'),
(60,'Individual','Philippines','Research and Development'),
(469,'Company','China','Accounting'),
(468,'Company','Sweden','Marketing'),
(467,'Individual','China','Human Resources'),
(445,'Company','Cameroon','Business Development'),
(63,'Individual','Greece','Human Resources'),
(446,'Individual','Indonesia','Sales'),
(447,'Individual','France','Support'),
(448,'Individual','Poland','Business Development'),
(449,'Company','Lithuania','Engineering'),
(450,'Company','Russia','Research and Development'),
(451,'Individual','Philippines','Product Management'),
(452,'Individual','Indonesia','Sales'),
(453,'Company','Madagascar','Human Resources'),
(454,'Individual','Peru','Product Management'),
(62,'Company','France','Product Management'),
(396,'Individual','China','Research and Development'),
(455,'Individual','Guatemala','Marketing'),
(456,'Individual','China','Research and Development'),
(457,'Individual','Canada','Research and Development'),
(458,'Company','Iran','Support'),
(459,'Individual','Costa Rica','Product Management'),
(460,'Individual','Ethiopia','Support'),
(461,'Individual','Indonesia','Engineering'),
(61,'Company','Philippines','Marketing'),
(462,'Company','Indonesia','Accounting'),
(463,'Company','Albania','Engineering'),
(464,'Individual','Portugal','Marketing'),
(465,'Individual','Greece','Product Management'),
(466,'Individual','Indonesia','Marketing'),
(968,'Individual','Thailand','Services'),
(492,'Individual','Colombia','Research and Development'),
(395,'Individual','Portugal','Human Resources'),
(393,'Company','China','Marketing'),
(324,'Individual','Uganda','Services'),
(325,'Individual','New Zealand','Training'),
(326,'Company','Indonesia','Marketing'),
(327,'Company','Iraq','Research and Development'),
(328,'Individual','Indonesia','Business Development'),
(78,'Individual','Greece','Legal'),
(329,'Individual','Slovenia','Business Development'),
(330,'Individual','Nepal','Engineering'),
(331,'Company','Thailand','Support'),
(977,'Individual','Serbia','Support'),
(332,'Company','Pakistan','Support'),
(333,'Individual','France','Training'),
(334,'Company','Finland','Training'),
(335,'Company','Russia','Sales'),
(77,'Company','Peru','Accounting'),
(336,'Individual','Israel','Business Development'),
(337,'Company','China','Legal'),
(338,'Individual','Niger','Sales'),
(339,'Individual','Russia','Human Resources'),
(340,'Individual','China','Support'),
(341,'Company','Bulgaria','Marketing'),
(342,'Individual','China','Services'),
(343,'Company','Russia','Business Development'),
(76,'Company','Syria','Legal'),
(344,'Company','Sweden','Engineering'),
(323,'Company','China','Support'),
(345,'Company','United Kingdom','Business Development'),
(322,'Company','Uganda','Engineering'),
(320,'Individual','Sweden','Product Management'),
(300,'Company','Thailand','Sales'),
(301,'Company','China','Training'),
(302,'Company','Japan','Human Resources'),
(303,'Individual','Tanzania','Marketing'),
(81,'Company','Saudi Arabia','Marketing'),
(979,'Individual','Jamaica','Engineering'),
(304,'Individual','China','Accounting'),
(305,'Company','Mongolia','Training'),
(306,'Company','Sweden','Services'),
(307,'Individual','China','Services'),
(308,'Individual','Japan','Accounting'),
(309,'Company','Brazil','Training'),
(310,'Company','Indonesia','Product Management'),
(311,'Individual','France','Marketing'),
(312,'Company','Brazil','Engineering'),
(80,'Company','China','Legal'),
(313,'Company','Russia','Legal'),
(314,'Individual','Argentina','Legal'),
(315,'Company','Colombia','Legal'),
(316,'Company','Ukraine','Human Resources'),
(317,'Company','Philippines','Accounting'),
(978,'Company','Indonesia','Engineering'),
(318,'Company','Colombia','Human Resources'),
(319,'Company','China','Services'),
(79,'Individual','Thailand','Marketing'),
(321,'Individual','Czech Republic','Human Resources'),
(976,'Individual','Indonesia','Training'),
(346,'Company','Indonesia','Sales'),
(347,'Company','Latvia','Support'),
(373,'Company','Sweden','Legal'),
(374,'Individual','Colombia','Legal'),
(375,'Company','Ukraine','Engineering'),
(72,'Individual','Palestinian Territory','Product Management'),
(376,'Individual','China','Accounting'),
(377,'Individual','China','Marketing'),
(378,'Individual','Cameroon','Accounting'),
(379,'Individual','Nigeria','Human Resources'),
(380,'Company','Philippines','Legal'),
(381,'Company','Philippines','Research and Development'),
(382,'Company','El Salvador','Human Resources'),
(383,'Individual','Montenegro','Sales'),
(71,'Individual','Philippines','Sales'),
(384,'Company','China','Training'),
(385,'Individual','China','Training'),
(386,'Company','China','Legal'),
(973,'Individual','Croatia','Support'),
(387,'Company','Bolivia','Accounting'),
(388,'Individual','Serbia','Research and Development'),
(389,'Company','Ukraine','Product Management'),
(390,'Individual','Azerbaijan','Legal'),
(391,'Individual','United States','Services'),
(70,'Company','Indonesia','Marketing'),
(996,'Company','Indonesia','Legal'),
(392,'Company','Brazil','Research and Development'),
(974,'Company','Sweden','Training'),
(372,'Individual','American Samoa','Sales'),
(371,'Company','Indonesia','Research and Development'),
(370,'Company','Finland','Training'),
(348,'Company','Sweden','Services'),
(349,'Company','Uzbekistan','Engineering'),
(350,'Individual','Brazil','Sales'),
(351,'Individual','Poland','Product Management'),
(75,'Company','Russia','Accounting'),
(352,'Individual','Latvia','Legal'),
(353,'Company','Greece','Product Management'),
(354,'Company','Ukraine','Research and Development'),
(355,'Individual','Indonesia','Support'),
(356,'Company','Spain','Services'),
(357,'Individual','France','Sales'),
(358,'Company','Japan','Research and Development'),
(394,'Company','Ukraine','Human Resources'),
(975,'Individual','Argentina','Legal'),
(74,'Company','Haiti','Business Development'),
(360,'Company','China','Services'),
(361,'Company','Sri Lanka','Research and Development'),
(362,'Company','Russia','Human Resources'),
(363,'Individual','China','Product Management'),
(364,'Individual','Mexico','Services'),
(365,'Individual','Ivory Coast','Support'),
(366,'Individual','Japan','Support'),
(367,'Company','Russia','Services'),
(73,'Company','Morocco','Product Management'),
(368,'Company','Philippines','Training'),
(369,'Company','North Korea','Marketing'),
(359,'Individual','Russia','Product Management'),
(878,'Company','France','Engineering'),
(107,'Company','Portugal','Services'),
(905,'Individual','Portugal','Marketing'),
(933,'Company','Poland','Product Management'),
(899,'Individual','Mexico','Human Resources'),
(923,'Individual','Canada','Research and Development'),
(922,'Individual','Honduras','Accounting'),
(3,'Individual','United States','Training'),
(911,'Individual','China','Business Development'),
(882,'Individual','Netherlands','Accounting'),
(884,'Company','Peru','Research and Development'),
(913,'Company','Portugal','Marketing'),
(924,'Company','Armenia','Marketing'),
(887,'Individual','China','Marketing'),
(937,'Company','Brazil','Human Resources'),
(885,'Company','Brazil','Training'),
(907,'Company','Sweden','Support'),
(886,'Company','Kazakhstan','Support'),
(903,'Individual','Indonesia','Research and Development'),
(914,'Company','Finland','Training'),
(935,'Company','Philippines','Training'),
(932,'Company','Mongolia','Training'),
(912,'Company','China','Training'),
(900,'Individual','Indonesia','Product Management'),
(934,'Company','Russia','Training'),
(904,'Individual','China','Sales'),
(902,'Individual','Thailand','Support'),
(901,'Individual','Portugal','Sales'),
(5,'Company','Guatemala','Sales'),
(936,'Individual','Argentina','Marketing'),
(7,'Individual','China','Legal'),
(917,'Company','Serbia','Human Resources'),
(891,'Individual','Russia','Product Management'),
(926,'Company','Russia','Sales'),
(893,'Individual','Indonesia','Legal'),
(880,'Company','France','Research and Development'),
(930,'Company','Indonesia','Marketing'),
(910,'Individual','Iran','Training'),
(918,'Company','Croatia','Accounting'),
(921,'Company','China','Human Resources'),
(906,'Individual','Philippines','Accounting'),
(916,'Company','Japan','Research and Development'),
(4,'Company','United States','Training'),
(928,'Company','Indonesia','Human Resources'),
(909,'Company','Grenada','Legal'),
(883,'Company','China','Training'),
(879,'Company','China','Human Resources'),
(915,'Company','Russia','Training'),
(925,'Individual','Canada','Support'),
(897,'Company','Russia','Human Resources'),
(927,'Individual','China','Services'),
(6,'Company','Canada','Training'),
(892,'Individual','France','Training'),
(929,'Company','China','Services'),
(2,'Individual','Vietnam','Marketing'),
(881,'Individual','Costa Rica','Training'),
(888,'Company','Indonesia','Engineering'),
(908,'Individual','China','Product Management'),
(895,'Individual','Brazil','Human Resources'),
(896,'Company','Philippines','Accounting'),
(931,'Individual','Bosnia and Herzegovina','Research and Development'),
(920,'Individual','Ethiopia','Business Development'),
(898,'Company','Indonesia','Sales'),
(894,'Company','Cuba','Business Development'),
(889,'Individual','France','Training'),
(8,'Individual','Brazil','Engineering'),
(919,'Company','Indonesia','Business Development'),
(890,'Company','South Africa','Training');